package com.example.project.dataSource

import android.media.MediaCodec.QueueRequest
import com.example.project.R
import com.example.project.adapter.QuestionItemAdapter
import com.example.project.model.QuestionModel

class QuestionDataSource {
    fun getListQuestion() : List<QuestionModel>{
        return listOf<QuestionModel>(
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,1,0,"Phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại là gì?","Phần mặt đường và lề đường.", "Phần đường xe chạy.","Phần đường xe cơ giới.", null, "Phần đường xe chạy."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,2,0, "Phương tiện tham gia giao thông đường bộ” gồm những loại nào?", "Phương tiện giao thông cơ giới đường bộ.", "Phương tiện giao thông thô sơ đường bộ và xe máy chuyên dùng.", "Cả ý 1 và ý 2", null, "Cả ý 1 và ý 2"),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,3,0, "Sử dụng rượu bia khi lái xe, nếu bị phát hiện thì bị xử lý như thế nào?", "Chỉ bị nhắc nhở.", "Bị xử phạt hành chính hoặc có thể bị xử lý hình sự tùy theo mức độ vi phạm.", "Không bị xử lý hình sự.", null, "Bị xử phạt hành chính hoặc có thể bị xử lý hình sự tùy theo mức độ vi phạm."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,4,0,"Bạn đang lái xe phía trước có một xe cứu thương đang phát tín hiệu ưu tiên bạn có được phép vượt hay không?", "Không được vượt.", "Được vượt khi đang đi trên cầu.", "Được phép vượt khi đi qua nơi giao nhau có ít phương tiện cùng tham gia giao thông.", "Được vượt khi đảm bảo an toàn.","Không được vượt."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,5,0,"Hành vi sử dụng xe mô tô để kéo, đẩy xe mô tô khác bị hết xăng đến trạm mua xăng có được phép hay không?","Chỉ được kéo nếu đã nhìn thấy trạm xăng.", "Chỉ được thực hiện trên đường vắng phương tiện cùng tham gia giao thông.", "Không được phép.", null, "Không được phép."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,6,0, "Bạn đang lái xe trong khu vực đô thi từ 22 giờ đến 5 giờ sáng hôm sau và cần vượt một xe khác, bạn cần báo hiệu như thế nào để đảm bảo an toàn giao thông?", "Phải báo hiệu bằng đèn hoặc còi.","Chỉ được báo hiệu bằng còi", "Phải báo hiệu bằng cả còi và đèn.", "Chỉ được báo hiệu bằng đèn.", "Chỉ được báo hiệu bằng đèn."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,7,0, "Người điều khiển phương tiện tham gia giao thông trong hầm đường bộ ngoài việc phải tuân thủ các quy tắc giao thông còn phải thực hiện những quy định nào dưới đây?", "Xe cơ giới, xe máy chuyên dùng phải bật đèn; xe thô sơ phải bật đèn hoặc có vật phát sáng báo hiệu; chỉ được dùng xe, đỗ xe ở nơi quy định.", "Xe cơ giới phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.", "Xe máy chuyên dùng phải bật đèn ngay cả khi đường hầm sáng; phải cho xe chạy trên một làn đường và chỉ chuyển làn ở nơi được phép; được quay đầu xe, lùi xe khi cần thiết.", null, "Xe cơ giới, xe máy chuyên dùng phải bật đèn; xe thô sơ phải bật đèn hoặc có vật phát sáng báo hiệu; chỉ được dùng xe, đỗ xe ở nơi quy định."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,8,0,"Trên đoạn đường hai chiều không có giải phân cách giữa, người lái xe không được vượt xe khác trong các trường hợp nào dưới đây?", "Xe bị vượt bất ngờ tăng tốc độ và cố tình không nhường đường.", "Xe bị vượt giảm tốc độ và nhường đường.", "Phát hiện có xe đi ngược chiều.", "Cả ý 1 và ý 3.", "Cả ý 1 và ý 3."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,9,0,"Khi điều khiển xe chạy với tốc độ dưới 60 km/h, người lái xe phải chủ động điều khiển xe như thế nào để đảm bảo an toàn giao thông?", "Chủ động giữ khoảng cách an toàn phù hợp với xe chạy liền trước xe của mình.", "Đảm bảo khoảng cách an toàn theo mật độ phương tiện, tình hình giao thông thực tế.", "Cả ý 1 và ý 2", null, "Cả ý 1 và ý 2"),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,10,0, "Để báo hiệu cho xe phía trước biết xe mô tô của bạn muốn vượt, bạn phải có tín hiệu như thế nào dưới đây?", "Ra tín hiệu bằng tay rồi cho xe vượt qua.", "Tăng ga mạnh để gây sự chú ý rồi cho xe vượt qua.", "Bạn phải có tín hiệu bằng đèn hoặc còi.", null, "Tăng ga mạnh để gây sự chú ý rồi cho xe vượt qua."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,11,0,"Khi điều khiển xe mô tô tay ga chạy xuống đường dốc dài, độ dốc cao, người lái xe cần thực hiện những thao tác nào dưới đây để đảm bảo an toàn?", "Giữ tay ga ở mức độ phù hợp, sử dụng phanh trước và phanh sau để giảm tốc độ.", "Nhả hết tay ga, tắt động cơ, sử dụng phanh trước và phanh sau để giảm tốc độ.", "Sử dụng phanh trước để giảm tốc độ kết hợp tắt chìa khóa điện của xe.", null, "Giữ tay ga ở mức độ phù hợp, sử dụng phanh trước và phanh sau để giảm tốc độ."),
            QuestionModel(QuestionItemAdapter.THE_FIRST_VIEW,12,0,"Tay ga trên xe mô tô hai bánh có tác dụng gì trong các trường hợp dưới đây?", "Để điều khiển xe chạy về phía trước.", "Để điều tiết công suất động cơ qua đó điều khiển tốc độ của xe.", "Để điều khiển xe chạy lùi.", "Cả ý 1 và ý 2.", "Cả ý 1 và ý 2."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,13,R.drawable.bien_cau_6, "Biển báo hiệu hình tròn có nền xanh lam có hình vẽ màu trắng là loại biển gì dưới đây?", "Biển báo nguy hiểm.", "Biển báo cấm.", "Biển báo hiệu lệnh phải thi hành.", "Biển báo chỉ dẫn.", "Biển báo hiệu lệnh phải thi hành."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,14,R.drawable.bien_cau_14, "Biển nào cấm xe rẽ trái?", "Biển 1.", "Biển 2.", "Cả hai biển.", null, "Biển 1."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,15,R.drawable.bien_cau_15, "Biển nào dưới đây các phương tiện không được phép đi vào?", "Biển 1.", "Biển 2.", "Biển 3.", "Biển 1 và 2.", "Biển 1 và 2."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,16,R.drawable.bien_cau_16, "Biển nào xe mô tô hai bánh không được đi vào?", "Biển 1.", "Biển 2.", "Biển 3.", null, "Biển 2."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,17,R.drawable.bien_cau_17,"Biển nào báo hiệu nguy hiểm giao nhau với đường sắt?", "Biển 1 và 2.", "Biển 1 và 3.", "Biển 2 và 3.", "Cả ba biển.", "Biển 1 và 3."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,18,R.drawable.bien_cau_18,"Biển nào báo hiệu “Đường giao nhau” của các tuyến đường cùng cấp?", "Biển 1.", "Biển 2.", "Biển 3.", null, "Biển 1."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,19,R.drawable.bien_cau_19,"Biển nào chỉ dẫn nơi bắt đầu đoạn đường dành cho người đi bộ?", "Biển 1.", "Biển 2.", "Biển 3.", null, "Biển 2."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,20,R.drawable.bien_cau_20,"Biển nào dưới đây báo hiệu hết cấm vượt?", "Biển 1.", "Biển 2.", "Biển 3.", "Biển 2 và 3.", "Biển 2 và 3."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,21,R.drawable.bien_cau_21, "Vạch kẻ đường nào dưới đây là vạch phân chia hai chiều xe chạy (vạch tim đường), xe không được lấn làn, không được đè lên vạch?'", "Vạch 1.", "Vạch 2.", "Vạch 3.", "Cả ba vạch.", "Vạch 2."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,22,R.drawable.bien_cau_22, "Xe nào được quyền đi trước trong trường hợp này?", "Xe mô tô.", "Xe cứu thương.", null, null, "Xe cứu thương."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,23,R.drawable.bien_cau_23,"Xe tải kéo mô tô ba bánh như hình này có đúng quy tắc giao thông không?", "Đúng.", "Không đúng.", null, null, "Không đúng."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,24,R.drawable.bien_cau_24, "Theo hướng mũi tên, những hướng nào xe mô tô được phép đi?", "Cả ba hướng.", "Hướng 1 và 2.", "Hướng 1 và 3.", "Hướng 2 và 3.", "Hướng 1 và 3."),
            QuestionModel(QuestionItemAdapter.THE_SECOND_VIEW,25,R.drawable.bien_cau_25, "Các xe đi theo hướng mũi tên, xe nào vi phạm quy tắc giao thông?", "Xe con, xe tải, xe khách", "Xe tải, xe khách, xe mô tô.", "Xe khách, xe mô tô, xe con.", "Cả bốn xe.", "Xe tải, xe khách, xe mô tô."),

        )
    }
}